name: 'Build Vue app'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
permissions:
  actions: write
  
jobs:
  build:
    name: build Vue application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
        
      - name: Push build on gh-pages
        run: |
          git checkout gh-pages
          mv dist/* .
          git add .
          git commit -m "New deployment"
          git push
